name: Deploy Service on EKS
on:
  workflow_call:
    secrets:
      CLUSTER_NAME:
        required: true
      AWS_REGION:
        required: true
      ECR_REPO_NAME:
        required: true
env:
  IMAGE_TAG: ${{ github.sha }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
jobs:
  build:
    name: Build and Deploy
    runs-on: smpcred-runner
    outputs:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Build
        run: npm run build

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_NAME:latest
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:latest

      - name: Deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          kubectl set image deployment/$ECR_REPO_NAME $ECR_REPO_NAME=$ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
