name: Deploy Service on EKS
on:
  workflow_call:
    inputs:
      CLUSTER_NAME:
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      ECR_REPO_NAME_PRD:
        required: true
env:
  IMAGE_TAG: ${{ github.sha }}
  CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME_PRD }}
jobs:
  build:
    name: Build and Deploy
    runs-on: smpcred-runner-prd
    outputs:
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_NAME:latest
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:latest
      
      - name: Format Deployment Name
        run: |
          echo "DEPLOYMENT_NAME=$(echo prod-user | sed -e 's/prod-//g)" >> $GITHUB_ENV"

      - name: Deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
