name: Deploy Service on EKS
on:
  workflow_call:
    secrets:
      CLUSTER_NAME:
        required: true
      AWS_REGION:
        required: true
      ECR_REPO_NAME:
        required: true

jobs:
  generate_release_image:
    name: Build and Push
    runs-on: smpcred-runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_NAME:latest
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:latest

  deploy_version_on_eks:
    name: Deploy new Image on EKS cluster
    needs: generate_release_image
    runs-on: smpcred-runner
    steps:
      - name: Deploy
        env:
          IMAGE_TAG: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO_NAME: ${{ inputs.ECR_REPO_NAME }}
        run: kubectl set image deployment/$ECR_REPO_NAME $ECR_REPO_NAME=$ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
